# Generated by Django 4.2.14 on 2024-07-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='duties',
            field=models.CharField(max_length=50, null=True, verbose_name='Duties'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.IntegerField(null=True, verbose_name='Salary'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.CharField(max_length=100, null=True, verbose_name='Skill'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=233, null=True, verbose_name='Name'),
        ),
    ]
