# Generated by Django 4.2.14 on 2024-07-24 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_vacancy_address_vacancy_company_name_vacancy_duties_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rezume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('surname', models.CharField(max_length=20, verbose_name='Surname')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Patronymic')),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=255)),
                ('skills', models.CharField(max_length=100, null=True, verbose_name='Skill')),
                ('pro_experience', models.CharField(max_length=255, verbose_name='Experience')),
                ('education', models.CharField(max_length=100, verbose_name='Educations')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.vacancy')),
            ],
        ),
    ]
