# Generated by Django 4.2.14 on 2024-07-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_rezume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezume',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Email'),
        ),
    ]
